name: deploy next-vercel to vercel
on: [push, pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - uses: actions/vercel-deployment@0.5.1
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          vercelOrgId: ${{ secrets.ORG_ID }}
          vercelProjectId: ${{ secrets.PROJECT_ID }}
          sourceDirectory: "src"
